name       : mpv
homepage   : https://mpv.io/
version    : 0.31.0
release    : 69
source     :
    - https://github.com/mpv-player/mpv/archive/v0.31.0.tar.gz : 805a3ac8cf51bfdea6087a6480c18835101da0355c8e469b6d488a1e290585a5
    - https://waf.io/waf-2.0.19 : ba63c90a865a9bcf46926c4e6776f9a3f73d29f33d49b7f61f96bc37b7397cef
    - https://github.com/2ion/mpv-bash-completion/archive/3.3.17.tar.gz : 355f9ae90638c730028e0b6a3ae6e9c09f5cb1ede27372f8a8cf7b0035020e97
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.video
summary    : mpv is a fork of mplayer2 and MPlayer. It shares some features with the former projects while introducing many more
description: |
    mpv is a fork of mplayer2 and MPlayer. It shares some features with the former projects while introducing many more. MPlayer's options parser was improved to behave more like other CLI programs, and many option names and semantics were reworked to make them more intuitive and memorable. mpv has a OpenGL based video output that is capable of many features loved by videophiles, such as video scaling with popular high quality algorithms, color management, and more.
    While mpv has no official GUI, it has a small controller that is triggered by mouse movement. mpv leverages the FFmpeg hwaccel APIs to support VDPAU, VAAPI and VDA video decode acceleration.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(dvdnav)
    - pkgconfig(ffnvcodec)
    - pkgconfig(gbm)
    - pkgconfig(libarchive)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libjpeg)
    - pkgconfig(libplacebo)
    - pkgconfig(libpulse)
    - pkgconfig(libva)
    - pkgconfig(luajit)
    - pkgconfig(rubberband)
    - pkgconfig(smbclient)
    - pkgconfig(uchardet)
    - pkgconfig(vapoursynth)
    - pkgconfig(vdpau)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xv)
    - python-docutils
    - vulkan-headers
rundeps    :
    - mpv-libs
patterns   :
    - libs :
        - /usr/lib64/lib*.so.*
    - libs-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
replaces   :
    - libs-devel : mpv-devel
environment: |
    export CFLAGS="$CFLAGS -DNDEBUG"
    export MPV_BASHCOMPGEN_MPV_CMD=../build/mpv
    export MBCversion=3.3.17
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration-on-nix-systems.patch
    install -m00755 $sources/waf-* ./waf
    %waf_configure  --confdir=/etc/mpv \
                    --libdir=%libdir% \
                    --enable-cdda \
                    --enable-dvbin \
                    --enable-dvdnav \
                    --enable-libarchive \
                    --enable-libmpv-shared \
                    --enable-libsmbclient \
                    --disable-debug

    tar xf "${sources}/${MBCversion}.tar.gz"
build      : |
    %waf_build

    pushd mpv-bash-completion-${MBCversion}
    %patch -p1 < $pkgfiles/0001-Fix-lua-binary.patch
    %make
    popd
install    : |
    %waf_install

    pushd mpv-bash-completion-${MBCversion}
    %make_install
    popd
