name       : mpv
homepage   : https://mpv.io/
version    : 0.34.1
release    : 99
source     :
    - https://github.com/mpv-player/mpv/archive/refs/tags/v0.34.1.tar.gz : 32ded8c13b6398310fa27767378193dc1db6d78b006b70dbcbd3123a1445e746
    - https://waf.io/waf-2.0.23 : 28a2e4583314a162cfcbffefb8a9202c1d7869040d30b5852da479b76d9c0491
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  :
    - multimedia.video
    - libs : multimedia.library
    - libs-devel : programming.devel
summary    : mpv is a fork of mplayer2 and MPlayer. It shares some features with the former projects while introducing many more
description: |
    mpv is a fork of mplayer2 and MPlayer. It shares some features with the former projects while introducing many more. MPlayer's options parser was improved to behave more like other CLI programs, and many option names and semantics were reworked to make them more intuitive and memorable. mpv has a OpenGL based video output that is capable of many features loved by videophiles, such as video scaling with popular high quality algorithms, color management, and more.
    While mpv has no official GUI, it has a small controller that is triggered by mouse movement. mpv leverages the FFmpeg hwaccel APIs to support VDPAU, VAAPI and VDA video decode acceleration.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(dvdnav)
    - pkgconfig(ffnvcodec)
    - pkgconfig(gbm)
    - pkgconfig(libarchive)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libjpeg)
    - pkgconfig(libplacebo)
    - pkgconfig(libpulse)
    - pkgconfig(libva)
    - pkgconfig(luajit)
    - pkgconfig(rubberband)
    - pkgconfig(uchardet)
    - pkgconfig(vapoursynth)
    - pkgconfig(vdpau)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xv)
    - python-docutils
    - vulkan-headers
rundeps    :
    - yt-dlp
    - libs :
        - yt-dlp
patterns   :
    - libs :
        - /usr/lib64/lib*.so.*
    - libs-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
replaces   :
    - libs-devel : mpv-devel
environment: |
    export CFLAGS="$CFLAGS -DNDEBUG"
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration-on-nix-systems.patch
    install -m00755 $sources/waf-* ./waf
    python3 %waf_configure \
        --confdir=/etc/mpv \
        --libdir=%libdir% \
        --enable-cdda \
        --enable-dvbin \
        --enable-dvdnav \
        --enable-gl-x11 \
        --enable-libmpv-shared \
        --disable-debug
build      : |
    python3 %waf_build
install    : |
    python3 %waf_install
