name       : mpv
homepage   : https://mpv.io/
version    : 0.32.0
release    : 73
source     :
    - https://github.com/mpv-player/mpv/archive/v0.32.0.tar.gz : 9163f64832226d22e24bbc4874ebd6ac02372cd717bef15c28a0aa858c5fe592
    - https://waf.io/waf-2.0.19 : ba63c90a865a9bcf46926c4e6776f9a3f73d29f33d49b7f61f96bc37b7397cef
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.video
summary    : mpv is a fork of mplayer2 and MPlayer. It shares some features with the former projects while introducing many more
description: |
    mpv is a fork of mplayer2 and MPlayer. It shares some features with the former projects while introducing many more. MPlayer's options parser was improved to behave more like other CLI programs, and many option names and semantics were reworked to make them more intuitive and memorable. mpv has a OpenGL based video output that is capable of many features loved by videophiles, such as video scaling with popular high quality algorithms, color management, and more.
    While mpv has no official GUI, it has a small controller that is triggered by mouse movement. mpv leverages the FFmpeg hwaccel APIs to support VDPAU, VAAPI and VDA video decode acceleration.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(dvdnav)
    - pkgconfig(ffnvcodec)
    - pkgconfig(gbm)
    - pkgconfig(libarchive)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libjpeg)
    - pkgconfig(libplacebo)
    - pkgconfig(libpulse)
    - pkgconfig(libva)
    - pkgconfig(luajit)
    - pkgconfig(rubberband)
    - pkgconfig(smbclient)
    - pkgconfig(uchardet)
    - pkgconfig(vapoursynth)
    - pkgconfig(vdpau)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xv)
    - python-docutils
    - vulkan-headers
rundeps    :
    - mpv-libs
patterns   :
    - libs :
        - /usr/lib64/lib*.so.*
    - libs-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
replaces   :
    - libs-devel : mpv-devel
environment: |
    export CFLAGS="$CFLAGS -DNDEBUG"
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration-on-nix-systems.patch
    install -m00755 $sources/waf-* ./waf
    %waf_configure  --confdir=/etc/mpv \
                    --libdir=%libdir% \
                    --enable-cdda \
                    --enable-dvbin \
                    --enable-dvdnav \
                    --enable-libarchive \
                    --enable-libmpv-shared \
                    --enable-libsmbclient \
                    --disable-debug
build      : |
    %waf_build
install    : |
    %waf_install
