name       : mpv
homepage   : http://mpv.io/
version    : 0.24.0
release    : 32
source     :
    - https://github.com/mpv-player/mpv/archive/v0.24.0.tar.gz : a41854fa0ac35b9c309ad692aaee67c8d4495c3546f11cb4cdd0a124195d3f15
    - http://www.freehackers.org/~tnagy/release/waf-1.9.7 : c7f9d47cc56559a4755088026dff2475726a9e0b110555ef5ae5aeddb21dfb4f
license    :
    - GPL-2.0
    - LGPL-2.1+
component  : multimedia.video
summary    : mpv is a fork of mplayer2 and MPlayer. It shares some features with the former projects while introducing many more.
description: |
    mpv is a fork of mplayer2 and MPlayer. It shares some features with the former projects while introducing many more. MPlayer's options parser was improved to behave more like other CLI programs, and many option names and semantics were reworked to make them more intuitive and memorable. mpv has a OpenGL based video output that is capable of many features loved by videophiles, such as video scaling with popular high quality algorithms, color management, and more.
    While mpv has no official GUI, it has a small controller that is triggered by mouse movement. mpv leverages the FFmpeg hwaccel APIs to support VDPAU, VAAPI and VDA video decode acceleration.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(gl)
    - pkgconfig(lcms2)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libguess)
    - pkgconfig(libmpg123)
    - pkgconfig(libpulse)
    - pkgconfig(libva-x11)
    - pkgconfig(libv4l2)
    - pkgconfig(lua-5.1)
    - pkgconfig(smbclient)
    - pkgconfig(uchardet)
    - pkgconfig(vapoursynth)
    - pkgconfig(vdpau)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xkbcommon)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xv)
    - libjpeg-turbo-devel
rundeps    :
    - mpv-libs
patterns   :
    - libs :
        - /usr/lib64/lib*.so.*
    - libs-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
replaces   :
    - libs-devel : mpv-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration-on-nix-systems.patch
    install -m 00755 $sources/waf-1.9.7 ./waf
    ./waf configure --prefix=/usr \
                    --confdir=/etc/mpv \
                    --libdir=%libdir% \
                    --enable-libmpv-shared \
                    --enable-vapoursynth \
                    --enable-zsh-comp
build      : |
    ./waf build
install    : |
    ./waf install --destdir="%installroot%"
