name       : mpv
homepage   : http://mpv.io/
version    : 0.16.0
release    : 14
source     :
    - https://github.com/mpv-player/mpv/archive/v0.16.0.tar.gz : fc3619de0ede16fbb023ac72589090e8e77fd9d9e03a81adc728105d50ef38ba
license    :
    - GPL-2.0
    - LGPL-2.1+
summary    : mpv is a fork of mplayer2 and MPlayer. It shares some features with the former projects while introducing many more.
description: |
    mpv is a fork of mplayer2 and MPlayer. It shares some features with the former projects while introducing many more. MPlayer's options parser was improved to behave more like other CLI programs, and many option names and semantics were reworked to make them more intuitive and memorable. mpv has a OpenGL based video output that is capable of many features loved by videophiles, such as video scaling with popular high quality algorithms, color management, and more.
    While mpv has no official GUI, it has a small controller that is triggered by mouse movement. mpv leverages the FFmpeg hwaccel APIs to support VDPAU, VAAPI and VDA video decode acceleration.
builddeps:
    - pkgconfig(vdpau)
    - pkgconfig(libavcodec)
    - pkgconfig(lcms2)
    - pkgconfig(libpulse)
    - pkgconfig(gl)
    - pkgconfig(x11)
    - pkgconfig(libva-x11)
    - pkgconfig(libbluray)
    - pkgconfig(dvdread)
    - pkgconfig(dvdnav)
    - pkgconfig(lua-5.1)
    - pkgconfig(libass)
    - pkgconfig(libmpg123)
    - pkgconfig(alsa)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xv)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(jack)
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration-on-nix-systems.patch
    ./bootstrap.py
    ./waf configure --prefix=/usr --confdir=/etc/mpv --enable-libmpv-shared
build      : |
    ./waf build
install    : |
    ./waf install --destdir="%installroot%"
