name       : mpv
homepage   : http://mpv.io/
version    : 0.17.0
release    : 17
source     :
    - https://github.com/mpv-player/mpv/archive/v0.17.0.tar.gz : 602cd2b0f5fc7e43473234fbb96e3f7bbb6418f15eb8fa720d9433cce31eba6e
license    :
    - GPL-2.0
    - LGPL-2.1+
component  : multimedia.video
summary    : mpv is a fork of mplayer2 and MPlayer. It shares some features with the former projects while introducing many more.
description: |
    mpv is a fork of mplayer2 and MPlayer. It shares some features with the former projects while introducing many more. MPlayer's options parser was improved to behave more like other CLI programs, and many option names and semantics were reworked to make them more intuitive and memorable. mpv has a OpenGL based video output that is capable of many features loved by videophiles, such as video scaling with popular high quality algorithms, color management, and more.
    While mpv has no official GUI, it has a small controller that is triggered by mouse movement. mpv leverages the FFmpeg hwaccel APIs to support VDPAU, VAAPI and VDA video decode acceleration.
builddeps:
    - pkgconfig(alsa)
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(lcms2)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libguess)
    - pkgconfig(libmpg123)
    - pkgconfig(libpulse)
    - pkgconfig(libva-x11)
    - pkgconfig(lua-5.1)
    - pkgconfig(smbclient)
    - pkgconfig(vdpau)
    - pkgconfig(x11)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xv)
    - libjpeg-turbo-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration-on-nix-systems.patch
    ./bootstrap.py
    ./waf configure --prefix=/usr --confdir=/etc/mpv --libdir=%libdir% --enable-libmpv-shared
build      : |
    ./waf build
install    : |
    ./waf install --destdir="%installroot%"
