name       : mpv
homepage   : https://mpv.io/
version    : 0.27.2
release    : 51
source     :
    - https://github.com/mpv-player/mpv/archive/v0.27.2.tar.gz : 2ad104d83fd3b2b9457716615acad57e479fd1537b8fc5e37bfe9065359b50be
    - https://waf.io/waf-1.9.15 : 85e76e38df9a4d45a6f73383f02f1438a5da39890e28c483101b2c16d2a63663
    - https://github.com/2ion/mpv-bash-completion/archive/3.3.16.tar.gz : 9b8fe4ab052ce514520005f04857cf1ce401dae6422467799d1da581dc4ee9ae
license    :
    - LGPL-2.1
    - GPL-3.0
component  : multimedia.video
summary    : mpv is a fork of mplayer2 and MPlayer. It shares some features with the
    former projects while introducing many more.
description: |
    mpv is a fork of mplayer2 and MPlayer. It shares some features with the former projects while introducing many more. MPlayer's options parser was improved to behave more like other CLI programs, and many option names and semantics were reworked to make them more intuitive and memorable. mpv has a OpenGL based video output that is capable of many features loved by videophiles, such as video scaling with popular high quality algorithms, color management, and more.
    While mpv has no official GUI, it has a small controller that is triggered by mouse movement. mpv leverages the FFmpeg hwaccel APIs to support VDPAU, VAAPI and VDA video decode acceleration.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(gl)
    - pkgconfig(lcms2)
    - pkgconfig(libass)
    - pkgconfig(libarchive)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libguess)
    - pkgconfig(libmpg123)
    - pkgconfig(libpulse)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libva-x11)
    - pkgconfig(lua-5.1)
    - pkgconfig(smbclient)
    - pkgconfig(uchardet)
    - pkgconfig(vapoursynth)
    - pkgconfig(vdpau)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xkbcommon)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xv)
rundeps    :
    - mpv-libs
patterns   :
    - libs :
        - /usr/lib64/lib*.so.*
    - libs-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
replaces   :
    - libs-devel : mpv-devel
setup      : |
    export CFLAGS="$CFLAGS -I/usr/include/lua5.1"
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration-on-nix-systems.patch
    %patch -p1 < $pkgfiles/0002-vaapi-Use-libva2-message-callbacks.patch
    install -m 00755 $sources/waf-* ./waf
    %waf_configure  --confdir=/etc/mpv \
                    --libdir=%libdir% \
                    --enable-cdda \
                    --enable-dvbin \
                    --enable-dvdread \
                    --enable-dvdnav \
                    --enable-libarchive \
                    --enable-libmpv-shared \
                    --enable-libsmbclient \
                    --enable-zsh-comp \
                    --disable-debug

    tar xf "${sources}/3.3.16.tar.gz"
build      : |
    export CFLAGS="$CFLAGS -I/usr/include/lua5.1"
    %waf_build

    pushd mpv-bash-completion-3.3.16
    %patch -p1 < $pkgfiles/0001-Fix-lua-binary.patch
    export MPV_BASHCOMPGEN_MPV_CMD=../build/mpv
    %make
    popd
install    : |
    export CFLAGS="$CFLAGS -I/usr/include/lua5.1"
    %waf_install

    pushd mpv-bash-completion-3.3.16
    export MPV_BASHCOMPGEN_MPV_CMD=../build/mpv
    %make_install
    popd

